wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714667221.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.11.8
      5: 0.16.5
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
