wandb_version: 1

learning_rate:
  desc: null
  value: 0.1
architecture:
  desc: null
  value: ResNet18
dataset:
  desc: null
  value: CIFAR-10
epochs:
  desc: null
  value: 20
deterministic:
  desc: null
  value: false
imb_degree:
  desc: null
  value: '0.1'
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716907702.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 7
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.16.5
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: epoch
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
      - 3
    - 1: train_accuracy
      5: 1
      6:
      - 1
      - 3
    - 1: test_loss
      5: 1
      6:
      - 1
      - 3
    - 1: test_accuracy
      5: 1
      6:
      - 1
      - 3
